# Generated by Django 3.2.20 on 2025-01-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='compare_price',
            new_name='purchase_price',
        ),
    ]
