# Generated by Django 3.2.20 on 2025-01-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_compare_price_product_purchase_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='purchase_price',
            new_name='compare_price',
        ),
    ]
