# Generated by Django 3.2.20 on 2025-01-27 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='country_region',
        ),
    ]
